### ISSUE TITLE
Failed to connect to card: Card is invalid or cannot be handled

### ISSUE THREAD

**Issue by morphinz** [darconeous/resin-SimpleCardAuth#1]
@darconeous Hello sir.

I have Omnikey 6121 SC with "Akis" sim card in it. Sim= "akiskart.com.tr"
Akis has a java program "Akia" and its showing inside the card. But the program hasn't API or DOC. 
<a href="https://github.com/darconeous/resin-SimpleCardAuth/blob/master/opensc/src/libopensc/card-akis.c">OpenSC Akis GitHub page.</a>

I'm devoloping something for Tubitak and i need to read sim card without akia, using linux from terminal. I just need to catch "username" information for my shell. I will access to rsa or dsa keys if its necessary.
I installed pkcs11-tool and pkcs15-tool. I think 15 is the correct one for my SC but both are didn't find the sim card but the java program "akia" working well.. 

I used latest Driver of 6121: <a href="https://www.hidglobal.com/drivers?field_driver_brand_tid_selective=24&field_driver_product_reference_nid_selective=All&field_driver_operating_systems_tid_selective=All">ifdokccid_linux_i686-v4.2.8.tar.gz</a>
I'm using Ubuntu 16.04

---

root@xx:/home/xx# opensc-tool --atr
Using reader with a card: OMNIKEY AG 6121 USB mobile 00 00
3b:9f:96:81:31:fe:45:80:67:55:45:4b:41:45:12:92:31:80:73:b3:a1:80:6a

---

root@xx:/home/xx# opensc-tool -f
Using reader with a card: OMNIKEY AG 6121 USB mobile 00 00
3f00 [MasterFile      ] type: DF, size: 0
select[N/A] lock[N/A] delete[N/A] create[N/A] rehab[N/A] inval[N/A] list[N/A] 

sc_list_files() failed: Not supported

---

root@xx:/home/xx# pkcs15-tool -L
Using reader with a card: OMNIKEY AG 6121 USB mobile 00 00
Failed to connect to card: Card is invalid or cannot be handled

---

root@xx:/home/xx# pkcs11-tool -L
Available slots:
Slot 1 (0x1): OMNIKEY AG 6121 USB mobile 00 00
  (empty)

---

After all these i found you and this project but when i start this program (on ubuntu 16.04) im getting these errors:

```
./start 
Starting up...
+ ./set_root_pw.sh
./start: 5: ./start: ./set_root_pw.sh: Permission denied
+ modprobe -r pn533
+ modprobe -r nfc
+ /etc/init.d/pcscd start
[ ok ] Starting pcscd (via systemctl): pcscd.service.
+ /usr/sbin/sshd
+ cat
+ ./SimpleCardAuth/auth-loop.sh
./SimpleCardAuth/auth-loop.sh: 15: ./SimpleCardAuth/auth-loop.sh: cannot create /sys/class/gpio/export: Permission denied
./SimpleCardAuth/auth-loop.sh: 16: ./SimpleCardAuth/auth-loop.sh: cannot create /sys/class/gpio/export: Permission denied
./SimpleCardAuth/auth-loop.sh: 17: ./SimpleCardAuth/auth-loop.sh: cannot create /sys/class/gpio/gpio27/direction: Directory nonexistent
./SimpleCardAuth/auth-loop.sh: 18: ./SimpleCardAuth/auth-loop.sh: cannot create /sys/class/gpio/export: Permission denied
./SimpleCardAuth/auth-loop.sh: 19: ./SimpleCardAuth/auth-loop.sh: cannot create /sys/class/gpio/gpio22/direction: Directory nonexistent
Starting Auth Loop
./SimpleCardAuth/auth-loop.sh: 35: ./SimpleCardAuth/auth-loop.sh: cannot create /sys/class/gpio/gpio17/direction: Directory nonexistent
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
```

Thank you for your help.

**Comment by darconeous** [comment]
This repository contains the sources for a docker container intended for ARM platforms (See [resin.io](https://resin.io/) for more info).

I think what you really want is [here](https://github.com/darconeous/SimpleCardAuth).

**Comment by darconeous** [comment]
Also, I don't know anything about the "Akis" card. [SimpleCardAuth](https://github.com/darconeous/SimpleCardAuth) was written for cards that have a [PIV](https://en.wikipedia.org/wiki/FIPS_201) app on them, although it could possibly be modified to work with other types of cards.
